version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
    ports:
      - 3306:3306